/****** SSMS 中 SelectTopNRows 命令的指令碼  ******/
DECLARE @TABLE TABLE(COL NVARCHAR(50))
INSERT INTO @TABLE
SELECT DISTINCT [Marital]
FROM [Data_Mining].[bank].[AllData]
DECLARE @TABLEIDX TABLE(COL NVARCHAR(50),IDX int)
INSERT INTO @TABLEIDX
SELECT DISTINCT [COL],ROW_NUMBER() OVER(ORDER BY COL)
FROM @TABLE
DECLARE @COLOneHotEncoding TABLE(COL NVARCHAR(50),OneHotEncoding NVARCHAR(MAX))
--外層迴圈
DECLARE @MIN INT=(SELECT MIN(IDX) FROM @TABLEIDX)
DECLARE @MAX INT=(SELECT MAX(IDX) FROM @TABLEIDX)
--內層迴圈
DECLARE @MIN_IN INT =@MIN
DECLARE @MAX_IN INT=@MAX
WHILE(@MIN<=@MAX)
BEGIN
	DECLARE @JOBS varchar(MAX)=(SELECT COL FROM @TABLEIDX WHERE IDX=@MIN);
	DECLARE @OneHotEncoding NVARCHAR(MAX)='';
	SET @OneHotEncoding='';
	SET @MIN_IN=1;
	WHILE(@MIN_IN<=@MAX_IN)
	BEGIN
		IF(@OneHotEncoding<>'') 
			SELECT @OneHotEncoding=@OneHotEncoding+',';
		IF(@MIN=@MIN_IN)
			SELECT @OneHotEncoding=@OneHotEncoding+'1';
		ELSE
			SELECT @OneHotEncoding=@OneHotEncoding+'0';
		SET @MIN_IN=@MIN_IN+1;
	END
	INSERT INTO @COLOneHotEncoding
	VALUES(@JOBS,@OneHotEncoding)
SET @MIN=@MIN+1;
END
SELECT * FROM @COLOneHotEncoding